# Generated by Django 3.2 on 2022-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserveapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservemodel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.CharField(max_length=50, verbose_name='チェックイン')),
                ('time1', models.CharField(max_length=50, verbose_name='開始')),
                ('checkout', models.CharField(max_length=50, verbose_name='チェックアウト')),
                ('time2', models.CharField(max_length=50, verbose_name='終了')),
                ('category', models.CharField(choices=[('A', 'A会議室'), ('B', 'B会議室')], max_length=50, verbose_name='予約可能部屋')),
            ],
        ),
    ]
